services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379

  node:
    build: .
    container_name: node-twikkL
    ports:
      - 8000:8000
    depends_on:
      - mongodb

volumes:
  mongodb_data: